name: build

on:
  pull_request: {}
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - run: chmod +x ./gradlew

    - name: Lint
      run: ./gradlew lintKotlin

    - name: Test
      run: ./gradlew test

    - name: Build
      run: ./gradlew build
